let shopItemsData = [{
        id: "H001",
        name: "Combo Escuadra",
        price: 2069.99,
        desc: "Combo Escuadra Nivel Escuadra Sombrero Carpintero Madera",
        img: "images/img-1.jpg",
    },
    {
        id: "H002",
        name: "Kit Fresas Avellanador",
        price: 1399,
        desc: "Kit Fresas Avellanador Biselador Mechas 3, 4, 6, 8, 10mm",
        img: "images/img-2.jpg",
    },
    {
        id: "H003",
        name: "Plantilla Guia Agujeros",
        price: 3899,
        desc: "Plantilla Guia Agujeros Ocultos Doble Carpinteria Soporte",
        img: "images/img-3.jpg",
    },
    {
        id: "H004",
        name: "Motosierra a nafta",
        price: 17683,
        desc: "Motosierra a nafta Kushiro 51cc K5220 2.2kW",
        img: "images/img-4.jpg",
    },
    {
        id: "H005",
        name: "Juego Set Formones",
        price: 1612.10,
        desc: "Juego Set Formones 5 Unidades Carpinteria",
        img: "images/img-5.jpg",
    },
    {
        id: "H006",
        name: "Taladro Manual",
        price: 7000,
        desc: "Taladro Manual Carpinteria Berbiqui Truper Bc12m 300 Mm 12",
        img: "images/img-6.jpg",
    },
    {
        id: "H007",
        name: "Prensa Sargento",
        price: 571.23,
        desc: "Prensa Sargento 50 X 150 Carpinteria",
        img: "images/img-7.jpg",
    },
    {
        id: "H008",
        name: "Prensa De Mano",
        price: 157.25,
        desc: "Prensa De Mano Carpintería Con Muela 100mm Cortag",
        img: "images/img-8.jpg",
    },
    {
        id: "H009",
        name: "Kit De 8 Herramientas",
        price: 5389.6,
        desc: "Kit De 8 Herramientas De Carpinteria Profesional - Japonesa.",
        img: "images/img-9.jpg",
    },
]